### ISSUE TITLE
Capture video frames from animation

### ISSUE THREAD

**Issue by raphaelschwinger** [raphaelschwinger/cone_reconstruction#15]
We should capture at least 24 frames per second while the animation is running.

## Deliverables 
* blender script to export frames for each camera

**Comment by rxxxxxxb** [comment]
Found a Similar issue on  Stackexchange.

https://blender.stackexchange.com/questions/49037/create-a-screencast-with-exactly-one-image-per-animation-frame

**Comment by raphaelschwinger** [comment]
maybe we can work with video files: https://vuamitom.github.io/2019/12/13/fast-iterate-through-video-frames.html
Might be easier to get them and handle them with python should be possible
