### ISSUE TITLE
Add more realistic race track scene on Blender.

### ISSUE THREAD

**Issue by rxxxxxxb** [raphaelschwinger/cone_reconstruction#23]

**Comment by rxxxxxxb** [comment]
To make the Race-Track more realistic, we have to 

- [ ] Add Curve to the road.
- [ ] Add realistic reac-track background

**Comment by raphaelschwinger** [comment]
I would suggest to make a circle with at least 25m diameter.

**Comment by rxxxxxxb** [comment]
For a real-world scenario, I found an amazing addon called [pure-sky.](https://blendermarket.com/products/pure-sky) But my laptop is not powerful enough to handle/render all the variables.

**Comment by raphaelschwinger** [comment]
> For a real-world scenario, I found an amazing addon called [pure-sky.](https://blendermarket.com/products/pure-sky) But my laptop is not powerful enough to handle/render all the variables.

@rxxxxxxb Cool, but lets make the tracking not to hard ;-)

**Comment by rxxxxxxb** [comment]
> > For a real-world scenario, I found an amazing addon called [pure-sky.](https://blendermarket.com/products/pure-sky) But my laptop is not powerful enough to handle/render all the variables.
> 
> @rxxxxxxb Cool, but lets make the tracking not to hard ;-)

I couldn't render the pure-sky environment because of my hardware limitations. I added a basic skybox to make the rendering less stressful for my laptop.
